language: node_js
node_js:
  - '10'
cache:
  yarn: true

matrix:
  exclude:
    - os: linux
      dist: bionic
      services:
        - docker
      before_install:
        - docker run -d --publish 8500:8500 --publish 8546:8546 --env DATADIR=/data --env PASSWORD=password123 --volume /tmp/swarm-data:/data --interactive --tty "ethersphere/swarm:0.4.2" --nosync --maxpeers=0 --verbosity=4 --httpaddr=0.0.0.0 --nat=none --corsdomain="*" --ws --wsaddr=0.0.0.0 --wsorigins="*"
      script:
        - yarn build
        - yarn lint
        - yarn test:ci
  include:
    - os: osx
      env:
        - GETH_VERSION=geth-darwin-amd64-1.9.1-b7b2f60f
        - SWARM_VERSION=swarm-darwin-amd64-0.4.2-3cdc45ee
        - DATADIR=/data
        - PASSWORD=password123
      before_install:
        - curl "https://ethswarm.blob.core.windows.net/builds/$GETH_VERSION.tar.gz" | tar -x && cd $GETH_VERSION
        - ./geth --datadir $DATADIR --password /password account new && cd ..
        - KEYFILE=`find $DATADIR | grep UTC | head -n 1` || true
        - BZZACCOUNT="`echo -n $KEYFILE | tail -c 40`" || true
        - curl "https://ethswarm.blob.core.windows.net/builds/$SWARM_VERSION.tar.gz" | tar -x && cd $SWARM_VERSION
        - ./swarm --bzzaccount=$BZZACCOUNT --password /password --datadir $DATADIR --nosync --maxpeers=0 --verbosity=4 --httpaddr=0.0.0.0 --nat=none --corsdomain="*" --ws --wsaddr=0.0.0.0 --wsorigins="*" &
      script:
        - yarn build
        - yarn lint
        - yarn test:ci

notifications:
  email:
    on_failure: change
