language: node_js
node_js:
  - '12'

cache:
  yarn: true

git:
  depth: false
  submodules: false
  quiet: true

matrix:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      before_install:
        - ./start_swarm_node.sh -d
    # macOS build takes too long to run in Travis
    # - os: osx
    #   env:
    #     - SWARM_VERSION=swarm-darwin-amd64-0.5.3-b0bc6a21
    #   before_install:
    #     - mkdir ~/data && echo "password" > ~/password
    #     - curl "https://ethswarm.blob.core.windows.net/builds/$SWARM_VERSION.tar.gz" | tar -x
    #     - ./$SWARM_VERSION/swarm --datadir ~/data --password ~/password --maxpeers=0 --verbosity=0 --httpaddr=0.0.0.0 --nat=none --corsdomain="*" --ws --wsaddr=0.0.0.0 --wsorigins="*" --enable-pinning &

script:
  - yarn build
  - yarn lint
  - yarn test:ci

notifications:
  email: false
