language: node_js
node_js:
  - '10'
cache:
  yarn: true

matrix:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      before_install:
        - docker run -d --publish 8500:8500 --publish 8546:8546 --env DATADIR=/data --env PASSWORD=password123 --volume /tmp/swarm-data:/data --interactive --tty "ethersphere/swarm:0.4.1" --nosync --maxpeers=0 --verbosity=4 --httpaddr=0.0.0.0 --nat=none --corsdomain="*" --ws --wsaddr=0.0.0.0 --wsorigins="*"
      script:
        - yarn test:ci
